fixed conflicts
w-alanna/Darts pull request #7
Opened 2023-11-10 14:52 UTC by w-alanna

2023-11-10 15:52 UTC, bpbond requested changes
Hi @w-alanna thanks for starting this! See one comment below.

Also, a hint: remember that R is heavily parallelized. Is there a way to generate the point x's and y's that doesn't involve a loop?

2023-11-10 15:52 UTC, bpbond commented on darts.R
> -points <- matrix(nrow=num_darts, ncol=2)
I think a `data.frame` will be easier to work down the line, so for example:
```r
points <- data.frame(x = rep(NA, num_darts), y = rep(NA, num_darts))
```

2023-11-17 19:37 UTC, melatg0 requested changes
The variable raduis is spelled wrong, if changed it may be better for clarity.

2023-11-17 19:44 UTC, melatg0 approved these changes
Thanks Alanna!

2023-11-17 19:45 UTC, merged